
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_one_development

  # The password associated with the postgres role (username).
  #password:

  # Connect on a TCP socket. Omitted by default since the client uses a
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: blog_one_test

#
production:
  <<: *default
  database: blog_one_production
